// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyalaairoazxqyyuubbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5YWxhYWlyb2F6eHF5eXV1YmJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTQ0MDQsImV4cCI6MjA1NDY3MDQwNH0.bwj0AraJrkTQ_TnljV482Z-h_J93ELv4UhVw9kA9z4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);